
[workspace.package]
version = "1.0.1"
edition = "2024"
license = "GPL-3.0"
keywords = ["graphics"]
repository = "https://github.com/Feeflak/SCAL"
authors = ["feeflak"]

[workspace.dependencies]
scal-ipc-macros = { path = "scal-ipc-macros", version = "1.0.1"}
scal-core = { path = "scal-core", version = "1.0.1" }
[workspace]
members = [
        "scal-core",
        "scal-ipc",
        "scal-ipc-macros",
        "scal-runtime",
        "./examples/audio",
        "./examples/code",
        "./examples/code_window",
        "./examples/git_clone",
        "./examples/image",
        "./examples/simple",
        "./examples/svg",
        "./examples/terminal",
        "./examples/text",
        "./examples/scroll",
        "./ign_projects/ign"
]
