[package]
name = "scal-core"
readme = "../readme.md"
description = "Core api code used for declearing animations on the user side, and later sending it serialized over ipc to the runtime."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true

[dependencies]
scal-ipc-macros.workspace = true
bytemuck="1.25.1"
glam = { version = "0.33.2", features = ["bytemuck", "serde"] }
uuid = { version = "1.23.4", features = ["v4", "v5", "serde"] }
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
