[package]
name = "scal-ipc"
readme = "../readme.md"
description = "Contains code needed for ipc communication beetween the user animation and the SCAL runtime."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true

[dependencies]
scal-core.workspace = true
scal-ipc-macros.workspace = true
bincode = "1.3"
